In [4]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [21]:
from sklearn.datasets import fetch_california_housing
fetch_housing = fetch_california_housing()

In [24]:
housing_df = pd.DataFrame(fetch_housing['data'], columns = fetch_housing['feature_names'])
housing_df['target'] = fetch_housing['target']
housing_df.columns = housing_df.columns.str.lower()

housing_df.head()

,medinc,houseage,averooms,avebedrms,population,aveoccup,latitude,longitude,target
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422